name: main

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: docker build -t test-react .
      - name: stop container
        run: docker stop test-react
        continue-on-error: true
      - name: remove image
        run: docker rm test-react
        continue-on-error: true
      - name: run image
        run: docker run -d --name reacto -p 3000:80 test-react
